drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_TYPE_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists Entreprise
drop table if exists Individu
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists Entreprise
drop table if exists Individu
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists Entreprise
drop table if exists Individu
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_FOURNISSEUR
drop table if exists ADRESS
drop table if exists Commande
drop table if exists LIGNE_COMMANDE
drop table if exists T_ARTICLE
drop table if exists T_CLIENT
drop table if exists T_FOURNISSEUR
